version: '3'

services:
  rtmp-server:
    build:
      context: ./rtmp-server
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"  # HLS
    volumes:
      - ./recordings:/recordings
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=local
      - USE_LIGHTSAIL_BUCKET=true
      - API_SERVER_URL=http://api-server:8000
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEBUG=true
    networks:
      app-network:
        aliases:
          - rtmp-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mock-video-source:
    build: ./mock-video-source
    depends_on:
      - rtmp-server
      - api-server
      - db
    networks:
      app-network:
        aliases:
          - mock-video-source

  api-server:
    build:
      context: ./api-server
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=local
      - POSTGRES_HOST=${LOCAL_POSTGRES_HOST}
      - POSTGRES_PORT=${LOCAL_POSTGRES_PORT}
      - POSTGRES_DB=${LOCAL_POSTGRES_DB:-recordings}
      - POSTGRES_USER=${LOCAL_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${LOCAL_POSTGRES_PASSWORD:-postgres}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - REDIS_URL=redis://redis:6379/0
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=30
      - SQL_ECHO=false
      - REDIS_SOCKET_TIMEOUT=30
      - REDIS_SOCKET_CONNECT_TIMEOUT=30
      - REDIS_RETRY_ON_TIMEOUT=true
      - REDIS_MAX_RETRIES=10
      - REDIS_RETRY_DELAY=1.0
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    networks:
      app-network:
        aliases:
          - api-server
    volumes:
      - ./recordings:/recordings
      - ./api-server/app:/app/app
      - ./api-server/alembic:/app/alembic
      - ./api-server/scripts:/app/scripts
    restart: unless-stopped

  celery-worker:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    image: drone-api-server
    working_dir: /app
    command: /app/celery_worker.sh
    volumes:
      - ./api-server:/app
      - ./api-server/celery_worker.sh:/app/celery_worker.sh
      - ./recordings:/recordings
    environment:
      - ENVIRONMENT=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB=recordings
      - REDIS_URL=redis://redis:6379/0
      - CELERY_CONCURRENCY=2
      - PYTHONPATH=/app
      - REDIS_SOCKET_TIMEOUT=30
      - REDIS_SOCKET_CONNECT_TIMEOUT=30
      - REDIS_RETRY_ON_TIMEOUT=true
      - REDIS_MAX_RETRIES=10
      - REDIS_RETRY_DELAY=1.0
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    restart: unless-stopped
    networks:
      app-network:
        aliases:
          - celery-worker
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2G'

  redis:
    image: redis:7-alpine
    container_name: drone-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --loglevel verbose
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      app-network:
        aliases:
          - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${LOCAL_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${LOCAL_POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${LOCAL_POSTGRES_DB:-recordings}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app-network:
        aliases:
          - db
    restart: unless-stopped

volumes:
  postgres_data:
  redis-data:

networks:
  app-network:
    driver: bridge 