version: '3'

services:
  rtmp-server:
    build:
      context: ./rtmp-server
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"  # HLS
    volumes:
      - ./recordings:/recordings
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=local
      - USE_LIGHTSAIL_BUCKET=true
      - API_SERVER_URL=http://api-server:8000
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEBUG=true
    networks:
      app-network:
        aliases:
          - rtmp-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mock-video-source:
    build: ./mock-video-source
    depends_on:
      - rtmp-server
      - api-server
      - db
    networks:
      app-network:
        aliases:
          - mock-video-source

  api-server:
    build:
      context: ./api-server
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=local
      - POSTGRES_HOST=${LOCAL_POSTGRES_HOST}
      - POSTGRES_PORT=${LOCAL_POSTGRES_PORT}
      - POSTGRES_DB=${LOCAL_POSTGRES_DB:-recordings}
      - POSTGRES_USER=${LOCAL_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${LOCAL_POSTGRES_PASSWORD:-postgres}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - DB_POOL_SIZE=20
      - DB_MAX_OVERFLOW=30
      - SQL_ECHO=false
      - TEMP_TOKEN_SECRET=${TEMP_TOKEN_SECRET}
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_started
    networks:
      app-network:
        aliases:
          - api-server
    volumes:
      - ./recordings:/recordings
      - ./api-server/app:/app/app
      - ./api-server/alembic:/app/alembic
      - ./api-server/scripts:/app/scripts
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${LOCAL_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${LOCAL_POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${LOCAL_POSTGRES_DB:-recordings}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app-network:
        aliases:
          - db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 