"""update_recording_schema_with_mp4_and_hls_paths

Revision ID: 2f40b47c801e
Revises: 58f1895de0de
Create Date: 2025-05-25 10:40:36.322805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f40b47c801e'
down_revision = '58f1895de0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('local_mp4_path', sa.String(length=1024), nullable=True))
    op.add_column('recordings', sa.Column('s3_mp4_path', sa.String(length=1024), nullable=True))
    op.add_column('recordings', sa.Column('local_hls_path', sa.String(length=1024), nullable=True))
    op.add_column('recordings', sa.Column('s3_hls_path', sa.String(length=1024), nullable=True))
    op.drop_column('recordings', 's3_path')
    op.drop_column('recordings', 'file_path')
    op.drop_constraint('user_device_association_device_id_fkey', 'user_device_association', type_='foreignkey')
    op.drop_constraint('user_device_association_user_id_fkey', 'user_device_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_device_association', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'user_device_association', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_device_association', type_='foreignkey')
    op.drop_constraint(None, 'user_device_association', type_='foreignkey')
    op.create_foreign_key('user_device_association_user_id_fkey', 'user_device_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('user_device_association_device_id_fkey', 'user_device_association', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.add_column('recordings', sa.Column('file_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('recordings', sa.Column('s3_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('recordings', 's3_hls_path')
    op.drop_column('recordings', 'local_hls_path')
    op.drop_column('recordings', 's3_mp4_path')
    op.drop_column('recordings', 'local_mp4_path')
    # ### end Alembic commands ### 