"""add user_id to recordings

Revision ID: 5d2d18dc4492
Revises: cdf76e840024
Create Date: 2025-04-08 11:22:11.588681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2d18dc4492'
down_revision = 'cdf76e840024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'recordings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recordings', type_='foreignkey')
    op.drop_column('recordings', 'user_id')
    # ### end Alembic commands ### 