"""create recordings table

Revision ID: cdf76e840024
Revises: 3e4411b49008
Create Date: 2025-04-08 20:08:11.588681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf76e840024'
down_revision = '3e4411b49008'  # This should point to the users table migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stream_name', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=1024), nullable=False),
        sa.Column('s3_path', sa.String(length=1024), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('file_size', sa.BigInteger(), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('environment', sa.String(length=50), nullable=False),
        sa.Column('recording_metadata', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_id'), 'recordings', ['id'], unique=False)
    op.create_index(op.f('ix_recordings_stream_name'), 'recordings', ['stream_name'], unique=False)
    op.create_index(op.f('ix_recordings_created_at'), 'recordings', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordings_created_at'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_stream_name'), table_name='recordings')
    op.drop_index(op.f('ix_recordings_id'), table_name='recordings')
    op.drop_table('recordings')
    # ### end Alembic commands ### 